### ISSUE TITLE
Missing Git/Composer tags

### ISSUE THREAD

**Issue by jrenggli** [Kephson/reint_file_timestamp#3]
Hi

First of all thanks for your extension and for sharing it in a git repository.

To unleash the full potential of Composer please use tags for every stable release.

e.g.
```
git tag 1.1.1 1e6ad2a
git tag 1.1.2 b2a8d38
git tag 1.1.3 1776884
git push --tags
```

**Comment by Kephson** [comment]
Hi thanks for the issue, I updated the repo with releases and tags.
